'use client'
import { useState } from 'react'
import { SiteNav, SiteFooter, useIsMobile } from './SiteChrome'
import MobileMenuDrawer from './MobileMenuDrawer'

const SECTIONS = [
  {
    h: '1. Acceptance of Terms',
    p: `By creating an account, browsing programs, or otherwise interacting with UniAsk (the "Service"), you agree to these Terms of Service. If you do not accept them in full, please stop using the Service. These Terms apply to every visitor and registered user.`,
  },
  {
    h: '2. About UniAsk',
    p: `UniAsk is an AI-powered university and program discovery platform. We help prospective students search, compare, and understand undergraduate, master's, and doctoral programs offered by universities worldwide. Features include personalized program matching, AI-generated summaries, saved programs, and conversational program research through the "Ask AI" chat.`,
  },
  {
    h: '3. Eligibility & Accounts',
    p: `The Service is intended for users aged 16 and above. You are responsible for the accuracy of the information you provide during sign-up and for keeping your credentials confidential. You agree to notify us promptly of any unauthorized access. We may suspend or terminate accounts that breach these Terms or remain inactive for prolonged periods.`,
  },
  {
    h: '4. Acceptable Use',
    p: `You agree not to (a) scrape, harvest, or otherwise extract data at scale, (b) attempt to reverse-engineer the AI models or infrastructure, (c) submit unlawful, deceptive, or harmful content, (d) use the Service to build a competing product, or (e) impersonate any person or institution. We may rate-limit or block requests that appear automated or abusive.`,
  },
  {
    h: '5. AI-Generated Content',
    p: `Portions of UniAsk are generated by large language models. Program details, admission guidance, tuition figures, and any other AI-produced text are provided for informational purposes only and may be incomplete or out of date. Always confirm requirements, deadlines, and costs on the university's official website before making an application decision.`,
  },
  {
    h: '6. Intellectual Property',
    p: `The Service — including its interface, brand assets, code, and curated data — is owned by UniAsk and its licensors and is protected by intellectual property laws. You receive a limited, non-exclusive, non-transferable license to use the Service for personal, non-commercial research. All rights not expressly granted are reserved.`,
  },
  {
    h: '7. Third-Party Content',
    p: `University names, logos, and program details displayed in the Service belong to their respective owners and are shown for informational and reference purposes only. Their inclusion does not imply endorsement or partnership unless explicitly stated. UniAsk is not affiliated with any university unless we clearly disclose such a relationship.`,
  },
  {
    h: '8. Disclaimer of Warranties',
    p: `The Service is provided "as is" and "as available", without warranties of any kind. We do not guarantee that information is accurate, complete, current, or that the Service will be uninterrupted, secure, or error-free.`,
  },
  {
    h: '9. Limitation of Liability',
    p: `To the maximum extent permitted by law, UniAsk and its team shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Service — including any admission, enrollment, or financial decision you make in reliance on Service content. Our aggregate liability for any claim will not exceed the fees you paid us, if any, in the twelve months preceding the claim.`,
  },
  {
    h: '10. Changes to the Service or Terms',
    p: `We continuously improve UniAsk and may add, modify, or remove features at any time. We may also update these Terms; material updates will be announced via the platform or by email. Your continued use of the Service after an update constitutes acceptance of the revised Terms.`,
  },
  {
    h: '11. Contact',
    p: `Questions about these Terms? Reach us at hello@uniask.ai and we'll respond within five business days.`,
  },
]

export default function TermsScreen({ user, onBack, onSignOut, onMyPrograms, onMyChats, onProfile, onFeedback, onTerms, onPrivacy }) {
  const isMobile = useIsMobile()
  const [menuOpen, setMenuOpen] = useState(false)

  return (
    <div style={{ minHeight: '100vh', background: '#fff', display: 'flex', flexDirection: 'column', fontFamily: 'Geist, sans-serif' }}>
      <SiteNav
        isMobile={isMobile}
        user={user}
        onOpenAuth={() => {}}
        onSignOut={onSignOut}
        onHome={onBack}
        onMyPrograms={onMyPrograms}
        onMyChats={onMyChats}
        onProfile={onProfile}
        onFeedback={onFeedback}
        onTerms={onTerms}
        onPrivacy={onPrivacy}
        onOpenMenu={() => setMenuOpen(true)}
      />

      <div style={{ flex: 1 }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: isMobile ? '24px 16px 48px' : '56px 32px 80px' }}>

          <h1 style={{ fontSize: isMobile ? 32 : 44, fontWeight: 500, color: '#000', lineHeight: 'normal', marginBottom: 8, letterSpacing: '-0.44px' }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, lineHeight: '22px', color: '#6B7280', marginBottom: isMobile ? 32 : 48 }}>
            Last updated: 15 January 2026
          </p>

          <p style={{ fontSize: 18, lineHeight: '26px', color: '#000', marginBottom: 40 }}>
            Welcome to UniAsk. These Terms of Service ("Terms") govern your access to and use of the UniAsk platform available at <span style={{ color: '#0162E3' }}>uniask.ai</span> and any related services (the "Service"). Please read them carefully.
          </p>

          {SECTIONS.map((s) => (
            <section key={s.h} style={{ marginBottom: 32 }}>
              <h2 style={{ fontSize: isMobile ? 20 : 22, fontWeight: 500, color: '#000', lineHeight: 'normal', letterSpacing: '-0.22px', marginBottom: 12 }}>
                {s.h}
              </h2>
              <p style={{ fontSize: 16, lineHeight: '24px', color: '#3A3A35', margin: 0 }}>
                {s.p}
              </p>
            </section>
          ))}
        </div>
      </div>

      <SiteFooter
        isMobile={isMobile}
        onHome={onBack}
        onMyPrograms={onMyPrograms}
        onMyChats={onMyChats}
        onTerms={onTerms}
        onPrivacy={onPrivacy}
      />

      {menuOpen && (
        <MobileMenuDrawer
          user={user}
          onClose={() => setMenuOpen(false)}
          onOpenAuth={() => {}}
          onSignOut={() => { setMenuOpen(false); onSignOut?.() }}
          onMyPrograms={() => { setMenuOpen(false); onMyPrograms?.() }}
          onMyChats={() => { setMenuOpen(false); onMyChats?.() }}
          onProfile={() => { setMenuOpen(false); onProfile?.() }}
          onFeedback={() => { setMenuOpen(false); onFeedback?.() }}
          onTerms={() => { setMenuOpen(false); onTerms?.() }}
          onPrivacy={() => { setMenuOpen(false); onPrivacy?.() }}
          onHome={() => { setMenuOpen(false); onBack?.() }}
        />
      )}
    </div>
  )
}
